### ISSUE TITLE
Do we still need the mediaPipeHack folder?

### ISSUE THREAD

**Issue by ezhang887** [NickL77/HandsfreeTV#1]
^ As title. Can we delete it?

**Comment by ezhang887** [comment]
@NickL77

**Comment by NickL77** [comment]
Do we? Is the all the image reading done in the inference script? @Bo887

**Comment by ezhang887** [comment]
Yeah, I believe so.
https://github.com/NickL77/HandsfreeTV/blob/6f50244fde7a61ebf44b42cc7121507bc8e4fed2/gesture_recognition/infer.py#L67-L83
